# Generated by Django 3.2.12 on 2022-07-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec_app', '0002_auto_20220726_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('pasw', models.CharField(max_length=50)),
            ],
        ),
    ]
