# Generated by Django 3.2.12 on 2022-07-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec_app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=30)),
                ('roll_no', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('pasw', models.CharField(max_length=50)),
                ('con_pass', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='sign',
        ),
    ]
