# Generated by Django 3.2.12 on 2022-07-29 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sec_app1.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sec_app1', '0004_add_book_add_student_issuedbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=100)),
                ('book_id', models.IntegerField()),
                ('book_category', models.CharField(max_length=100)),
                ('user_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='issue_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=100)),
                ('book_id', models.CharField(max_length=13)),
                ('issued_date', models.DateField(auto_now=True)),
                ('expiry_date', models.DateField(default=sec_app1.models.expiry)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='return_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=20)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='add_student',
            new_name='add_students',
        ),
        migrations.DeleteModel(
            name='add_book',
        ),
        migrations.DeleteModel(
            name='IssuedBook',
        ),
        migrations.RenameField(
            model_name='add_students',
            old_name='user',
            new_name='user_name',
        ),
    ]
