# Generated by Django 3.2.12 on 2022-07-29 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sec_app1', '0006_auto_20220729_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue_books',
            name='user_name',
        ),
    ]
