# Generated by Django 3.2.12 on 2022-07-30 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sec_app1.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sec_app1', '0007_remove_issue_books_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='issue_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=100)),
                ('book_id', models.CharField(max_length=13)),
                ('book_name', models.CharField(max_length=20)),
                ('student_name', models.CharField(max_length=20)),
                ('issued_date', models.DateField(auto_now=True)),
                ('expiry_date', models.DateField(default=sec_app1.models.expiry)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='issue_books',
        ),
    ]
