# Generated by Django 3.2.12 on 2022-07-30 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sec_app1', '0010_alter_issue_book_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue_book',
            name='user_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sec_app1.sign'),
        ),
    ]
