# Generated by Django 3.2.12 on 2022-07-30 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sec_app1', '0014_auto_20220730_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sign',
            old_name='user_name',
            new_name='user',
        ),
    ]
