# Generated by Django 3.2.12 on 2022-07-30 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sec_app1', '0016_auto_20220730_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('user_name', models.CharField(max_length=40)),
                ('pasw', models.CharField(max_length=50)),
                ('con_pass', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='signup',
        ),
        migrations.AlterField(
            model_name='add_books',
            name='user_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sec_app1.sign'),
        ),
        migrations.AlterField(
            model_name='add_students',
            name='user_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sec_app1.sign'),
        ),
        migrations.AlterField(
            model_name='issue_book',
            name='user_name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='sec_app1.sign'),
        ),
        migrations.AlterField(
            model_name='return_book',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sec_app1.sign'),
        ),
    ]
