# Generated by Django 3.2.12 on 2022-07-30 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sec_app1', '0019_auto_20220730_1205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='create',
            new_name='created',
        ),
    ]
