# Generated by Django 3.2.12 on 2022-07-31 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sec_app1', '0021_auto_20220730_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='return_books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=100)),
                ('book_id', models.CharField(max_length=13)),
                ('book_name', models.CharField(max_length=20)),
                ('student_name', models.CharField(max_length=20)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sec_app1.created')),
            ],
        ),
        migrations.RemoveField(
            model_name='add_book',
            name='status',
        ),
        migrations.DeleteModel(
            name='return_book',
        ),
    ]
