# Generated by Django 3.2.12 on 2022-08-12 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('pasw', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=30)),
                ('roll_no', models.IntegerField()),
                ('class_name', models.CharField(max_length=10)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('email', models.EmailField(max_length=50)),
                ('pasw', models.CharField(max_length=50)),
                ('con_pass', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='book_return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=100)),
                ('book_id', models.CharField(max_length=13)),
                ('book_name', models.CharField(max_length=20)),
                ('student_name', models.CharField(max_length=20)),
                ('return_date', models.DateField(auto_now=True)),
                ('author_name', models.CharField(max_length=100)),
                ('book_category', models.CharField(max_length=20)),
                ('user_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sec_app2.signup')),
            ],
        ),
    ]
