# Generated by Django 3.2.12 on 2022-08-12 03:55

from django.db import migrations, models
import sec_app2.models


class Migration(migrations.Migration):

    dependencies = [
        ('sec_app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=100)),
                ('book_id', models.CharField(max_length=13)),
                ('book_name', models.CharField(max_length=20)),
                ('author_name', models.CharField(max_length=100)),
                ('book_category', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('student_name', models.CharField(max_length=20)),
                ('issued_date', models.DateField(auto_now=True)),
                ('expiry_date', models.DateField(default=sec_app2.models.expiry)),
            ],
        ),
    ]
